# 启动端口
server:
  port: 5181

spring:
  application:
    name: eureka-kiba
# eureka客户端配置，配置要注册的服务查询中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5180/eureka

#      eureka:
#        client:
#          service-url:
#            defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka ֧ 注册多个eureka服务中心